version: "3.2"

networks:
  frontend:
  backend:


services:

  customer:
    image: banking/customer
    build: 
      context: ./customer
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: customerapi
    ports:
      - "5001:80"
    networks:
      - backend
      - frontend 
    depends_on:
      - mssqlserver

  identity:
    image: banking/identity
    build: 
      context: ./identity
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: identityapi
    ports:
      - "5002:80"
    networks:
      - backend
      - frontend 
    depends_on:
      - mssqlserver

  gateway:
    image: banking/gateway
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: gatewayapi
    ports:
      - "5000:80"
    networks:
      - backend
      - frontend 
    depends_on:
      - mssqlserver
      - customer
      - identity
      
  mssqlserver:
    image: "microsoft/mssql-server-linux"
    container_name: mssqldata
    ports:
      - "1402:1433" 
    networks:
      - backend
    environment:
      - SA_PASSWORD=Str0ngPassword!
      - ACCEPT_EULA="Y"